on:
  release:
    types: [created, edited]
jobs:
  build:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - name: "build artifact"
        run: |
          echo hello world
          echo test
          echo $GITHUB_REF
          env
