on:
  push
  # release:
  #   types: [created, edited]
jobs:
  build:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - name: "build artifact"
        uses: actions/checkout@v2
        run: |
          ls -l
          env GOOS="darwin" GOARCH="amd64" go build
          ls -l