on:
  release:
    types: [created, edited]
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: "unit tests"
        run: |
          echo "to be implemented"
      - name: build artifact
        id: artifact
        run: |
          env GOOS="darwin" GOARCH="amd64" go build -o destroyTF
          tar -czvf destroyTF.darwin.tar.gz destroyTF
      - name: install action npm modules
        run: |
          cd ./.github/actions/upload-asset
          yarn install
      - name: upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/actions/upload-asset
