on:
  push:
    branches:
      - master
    tags:
      - v[12].[0-9]+.[0-9]+
jobs:
  build:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - name: "build artifact"
        run: |
          echo hello world
          env
